version: "3.8"

services:
  app:
    build: .
    container_name: devsecops-demo-app
    ports:
      - "8080:80"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: demo_db
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: devsecops-demo-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
