name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t dvwa-app .

    - name: Run Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: dvwa-app
        format: json
        output: trivy-report.json

    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: trivy-report
        path: trivy-report.json

    - name: Run Semgrep
      run: |
        pip install semgrep
        semgrep scan --json --output semgrep-report.json

    - name: Upload Semgrep report
      uses: actions/upload-artifact@v4
      with:
        name: semgrep-report
        path: semgrep-report.json

    - name: Run ZAP Scan
      continue-on-error: true
      run: |
        docker run -t \
          -u root \
          -v $(pwd):/zap/wrk \
          ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
          -t https://example.com \
          -J zap-report.json \
          -I || true

    - name: Upload Reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
           semgrep-report.json
           trivy-report.json
           zap-report.json

    - name: Send to n8n
      run: |
        jq -n \
          --slurpfile trivy trivy-report.json \
          --slurpfile semgrep semgrep-report.json \
          --slurpfile zap zap-report.json \
          '{trivy: $trivy[0], semgrep: $semgrep[0], zap: $zap[0]}' > final-report.json

        curl -X POST https://unfitted-unsubtle-overdrive.ngrok-free.app  \
          -H "Content-Type: application/json" \
          -d @final-report.json
